image: "rust:latest"


 before_script:
   - apt-get update -yqq
   - apt-get install -yqq --no-install-recommends build-essential libssl-dev pkg-config

# Use cargo to test the project
test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
