[package]
name = "mover"
version = "0.1.0"
authors = ["Dylan Maccora <maccora17@gmail.com>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dev-dependencies]
reqwest = "0.8"